### ISSUE TITLE
How to highlight current route?

### ISSUE THREAD

**Issue by afunworm** [ShankyTiwari/ng-material-multilevel-menu#100]
I can't get the current route's menu item to highlight itself and I am doing the basic example from your repo with no extra customization.

**app.component.ts**
```
    mainNavItems = [
        { link: 'dashboard', icon: 'dashboard', label: 'Dashboard' },
        { link: 'help', icon: 'star', label: 'Help' }
    ];

    navConfig = {
        interfaceWithRoute: true
    };
```

The menu items, in this case `Dashboard` and `Help`, won't highlight themselves even if their perspective route was loaded. Am I missing something?

**Comment by ShankyTiwari** [comment]
Hi @afunworm , try the below configuration,
```javascript
config = {
    interfaceWithRoute: true,
    highlightOnSelect: true,
  };
```
Also, can you take a clone of [this repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo), This repo has almost all the examples, let me know if you have any issue.

Thanks for using `ng-material-multilevel-menu`.
