### ISSUE TITLE
support for @fortawesome/angular-fontawesome icons

### ISSUE THREAD

**Issue by eddiefrank** [ShankyTiwari/ng-material-multilevel-menu#114]
Hello
it is planned to support icons from @fortawesome/angular-fontawesome package
https://www.npmjs.com/package/@fortawesome/angular-fontawesome

**Comment by cityinspain** [comment]
FontAwesome icons are supported. All you need to do is specify the faIcon property for an item.
For example:
`
{
    label: "An item with a FontAwesome icon",
    faIcon: "fa-acorn" 
}    
`

**Comment by eddiefrank** [comment]
not working with  @fortawesome/angular-fontawesome package...
html template for the package should be:
<fa-icon [icon]="faCoffee"></fa-icon>

**Comment by cityinspain** [comment]
I understand now, sorry.

This project doesn't utilize the npm package, you have to go through FontAwesome's CDN. You can go to their website and sign up to get a link, which you've got to put in a <script> tag in your index.html.

Example:
`<script src="https://kit.fontawesome.com/<your_kit_id>.js" crossorigin="anonymous"></script>`

Hope this helps.
