### ISSUE TITLE
No provider for MultilevelMenuService!"

### ISSUE THREAD

**Issue by symeonmattes** [ShankyTiwari/ng-material-multilevel-menu#116]
Hi,

I have an angular8 project which I upgraded recently from angular7, since ng-material-multilevel@4.10.8 had some issues on the order. Now I have @4.12.2.

with `ng serve` the application works fine and the multilevel as expected.

However I've installed angular ssr as described in [universal](https://angular.io/guide/universal) and when when I run with the command:

`ng serve --prod --optimization=false`

or

`npm run build:ssr && npm run serve:ssr`

I receive the following error:

> main.96f1c69496e6c439b888.js:29505 ERROR NullInjectorError: StaticInjectorError(AppModule)[ListItemComponent -> MultilevelMenuService]: 
>   StaticInjectorError(Platform: core)[ListItemComponent -> MultilevelMenuService]: 
>     NullInjectorError: No provider for MultilevelMenuService!

I have made the following project in order to show the error I get which you can find in the link [angular8-ng-multilevel](https://github.com/symeonmattes/angular8-ng-multilevel)

Have you encountered this problem and how could I solve it?

Thanks

**Comment by ShankyTiwari** [comment]
Hey  @symeonmattes  Thanks for proving the code, I'll check and get back to you

**Comment by bennymeg** [comment]
Sam here...

I have fixed it temporarily like this: (add this code to your module)

```typescript
import { NgMaterialMultilevelMenuModule, ɵb } from 'ng-material-multilevel-menu';

@NgModule({
  imports: [
    NgMaterialMultilevelMenuModule,
    ...
  ],
  providers: [ ɵb ]
})
```

**Comment by ShankyTiwari** [comment]
Just out of curiosity, What is this `ɵb` @bennymeg, instance of a Service?

**Comment by ShankyTiwari** [comment]
Should  be fixed with latest version [4.12.4](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.12.4).

**Comment by bennymeg** [comment]
> Just out of curiosity, What is this `ɵb` @bennymeg, instance of a Service?

That's just the name that the angular compiler gave to your service.

**Comment by ShankyTiwari** [comment]
Hi @bennymeg Are you still getting this with the latest version of the plugin ?

**Comment by bennymeg** [comment]
I will test and let you know.

I think all you need to do is to export the service as well and update the docs to describe how to set it as a provider.

**Comment by ShankyTiwari** [comment]
Yeah, now the service now exported in favour of #131 and #117. Let me know if you still see the issue again, I'll check ASAP.

**Comment by bennymeg** [comment]
@symeonmattes  unfortunately it did not fix the problem.
Also I cannot use the `MultilevelMenuService`, did you exported it?

**Comment by ShankyTiwari** [comment]
Hi @bennymeg which version you are using? please use the latest one i.e. 5.0.1 [like this ].(https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo/blob/master/src/app/pages/more-configuration/expand-collapse/expand-collapse.component.ts#L67)

**Comment by bennymeg** [comment]
Sorry, everything works =]

**Comment by mrarguijo2** [comment]
> Me he encontrado con el mismo problema en producción (incluso sin ssr [ `'ng build --prod'`]).
> 
> Lo he arreglado temporalmente así: (agregue este código a su módulo)
> 
> ```ts
> importar  {  NgMaterialMultilevelMenuModule ,  ɵb  }  desde  'ng-material-multilevel-menu' ;
> 
> @ NgModule ( { 
>   importaciones : [ 
>     NgMaterialMultilevelMenuModule ,
>     ...
>   ] , 
>   proveedores : [  ɵb  ] 
> } )
> ```

Esto no me funciono

Esto me funciona perfecto

> ```ts
>import { MaterialModule } from './material/material.module';
>import { NgModule } from '@angular/core';
>import { BrowserModule } from '@angular/platform-browser';
>import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
>import { NgMaterialMultilevelMenuModule, MultilevelMenuService } from 'ng-material-multilevel-menu';
>
>@NgModule({
> declarations: [
>    ...
>  ],
>  imports: [
>    ....
>    NgMaterialMultilevelMenuModule
>  ],
>  providers: [ MultilevelMenuService ],
>  bootstrap: [AppComponent]
>})
>export class AppModule {
>
>}```
