### ISSUE TITLE
Is it possible to select item with id?

### ISSUE THREAD

**Issue by ersamrow** [ShankyTiwari/ng-material-multilevel-menu#117]
I want to select item with it's id:
      const item = {
        id: t.bID.toString(),
        label: t.bID + ': ' + t.bName,
        type: 1,
        icon: '',
        data: t,
        items: that.subList(t.bQueries),
        onSelected: function () {
          console.log('Block :' + t.bName);
        }
      };

**Comment by ShankyTiwari** [comment]
Hi @ersamrow this feature is not available yet, But I'll work on it later. Thanks

**Comment by ShankyTiwari** [comment]
Hi @ersamrow Added in [5.0.1](https://www.npmjs.com/package/ng-material-multilevel-menu/v/5.0.1#2-select-menu-by-id), sorry for the delay.
Let me know in case of any issue.

Thanks
