### ISSUE TITLE
Suggestion: indent submenu items

### ISSUE THREAD

**Issue by JoaoPortella** [ShankyTiwari/ng-material-multilevel-menu#12]
I think it might be a good idea to view the items as if they were displayed in a hierarchical tree.

Thanks for Component!

**Comment by ShankyTiwari** [comment]
By indentation, I assume you want some padding applied at the start of submenu items. If that the case we got that. 

Check the [demo](http://plugins.codershood.info/#/plugins/ngmm-plugin) or clone this [repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo) its has more demos.

Thanks

**Comment by JoaoPortella** [comment]
Sure.
I believe there is some conflict in my application.
Thanks!
