### ISSUE TITLE
Empty space over first item

### ISSUE THREAD

**Issue by esaesa** [ShankyTiwari/ng-material-multilevel-menu#120]
There is empty space over first item.
![image](https://user-images.githubusercontent.com/5354709/86521052-fa563600-be4b-11ea-8ef4-85f71039bc21.png)

**Comment by ShankyTiwari** [comment]
The padding applied to the menu is because of the Angular's `.mat-list-base` class, I'll Iook into it. Thanks for reporting.

**Comment by ShankyTiwari** [comment]
Fixed in [4.12.4](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.12.4)
