### ISSUE TITLE
Is it possible to set custom HTML Entries?

### ISSUE THREAD

**Issue by gabriel-gn** [ShankyTiwari/ng-material-multilevel-menu#127]
From the examples, we are currently able only to use a "label" and "icon" as list entry.
Is it possible to render custom html content instead?

**Comment by ShankyTiwari** [comment]
Hi @gabriel-gn , Sorry for the delay. I will check the possibilities how can implement  this with the current  setup. But for sure I understand  this would be extremely flexible  and useful.

Let me check and get back.

Thanks

**Comment by ShankyTiwari** [comment]
Hi @gabriel-gn Sorry for delay.

This feature is now added in version [5.5.1](https://www.npmjs.com/package/ng-material-multilevel-menu/v/5.5.1), The documentation is [here](https://github.com/ShankyTiwari/ng-material-multilevel-menu#3-building-custom-templates). You can try to use it, if you are using this plugin and please share your feedback.

Thanks
