### ISSUE TITLE
Support for badges

### ISSUE THREAD

**Issue by AMRALAA10** [ShankyTiwari/ng-material-multilevel-menu#128]
Can We set a right badge on menu item?

**Comment by ShankyTiwari** [comment]
Am not sure what do you mean by the right badge  @AMRALAA10 ?

**Comment by AMRALAA10** [comment]
Something like this
<img width="388" alt="Screen Shot 2020-08-31 at 10 30 53 AM" src="https://user-images.githubusercontent.com/11869944/91689482-46380980-eb75-11ea-8a3c-dcdd62000121.png">

**Comment by ShankyTiwari** [comment]
Hi @AMRALAA10 Sorry for the delay, please follow this [issue](https://github.com/ShankyTiwari/ng-material-multilevel-menu/issues/127#issuecomment-731813188).

Thanks

**Comment by ShankyTiwari** [comment]
Hi @AMRALAA10  Sorry for delay.

This feature is now added in version [5.5.1](https://www.npmjs.com/package/ng-material-multilevel-menu/v/5.5.1), The documentation is [here](https://github.com/ShankyTiwari/ng-material-multilevel-menu#3-building-custom-templates). You can try to use it, if you are using this plugin and please share your feedback.

Thanks
