### ISSUE TITLE
Selected item color

### ISSUE THREAD

**Issue by JoaoPortella** [ShankyTiwari/ng-material-multilevel-menu#13]
The color of the selected item does not appear in my application like your example. I believe that may be some conflict with some other component. Is there any class that can be modified to force the color change when an item is selected?

**Comment by ShankyTiwari** [comment]
Hi there,
You can give class name using ```configuration``` input to entire Menu. The selected Item has ```selected-amml-item``` class.
If it is possible for you to create a repo or Stackbliz that would be helpful.

Thanks

**Comment by JoaoPortella** [comment]
Hi,
Thanks for the quick response. Everything works fine on a new project. I believe there is some conflict when I use it with my template. I'll investigate and try to figure out the problem.

**Comment by ShankyTiwari** [comment]
Cool, let me know if something needs to be done from side.
