### ISSUE TITLE
Angular 10+ and Material 10+ Support

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ShankyTiwari/ng-material-multilevel-menu#130]
Hi,

Is this working with Angular 10+ and Material 10+? Do you have any plan to upgrade it to the latest versions?

**Comment by ShankyTiwari** [comment]
Hi @Sampath-Lokuge Have you tried in V 10? Let me know if it doesn't work, I am gonna update it in next weekend.

**Comment by Sampath-Lokuge** [comment]
Hi @ShankyTiwari 
Sure, I'll try that and come back again. Thanks!

**Comment by Sampath-Lokuge** [comment]
Please see this: #131

**Comment by ShankyTiwari** [comment]
Fixed in[ 4.12.4](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.12.4).
