### ISSUE TITLE
call selectedItem without click on any menu

### ISSUE THREAD

**Issue by apurv195** [ShankyTiwari/ng-material-multilevel-menu#133]
1. i have implemented **ng-material-multilevel-menu** in my angular project, it's working fine but, selectedItem call without click on any menu.
2. if i change route from my component without click on menu, the **selectedItem** function was call, so how can i prevent that

`<ng-material-multilevel-menu [configuration]='config' [items]='userAllMenus' (selectedItem)="selectedItem($event)" (selectedLabel)="selectedLabel($event)">
    </ng-material-multilevel-menu>`

`    selectedItem($event) {
        console.log('$event --->', $event);
    }`

**Comment by ShankyTiwari** [comment]
Hi @apurv195
Sorry for the delay.

I have added this feature in [5.0.1](https://www.npmjs.com/package/ng-material-multilevel-menu/v/5.0.1#3-structure-of-array-to-display-the-list), You can add one more property called as `dontEmit` in the node object as shown below. 

This property will apply to the current node only, it won't apply to it's children nodes. The default  behaviour will be the same, if you won't provide the`dontEmit` property.


```typescript
{
    label: 'Changing Colours',
    link: '/demo two',
    icon: 'favorite_border',
    activeIcon: 'favorite',
    dontEmit: true,
    navigationExtras: {
        queryParams: { order: 'popular', filter: 'new' },
    }
}
```

Let me know in case of any issue.

Thanks
