### ISSUE TITLE
Log appearing everytime an entry is clicked

### ISSUE THREAD

**Issue by hectoryo** [ShankyTiwari/ng-material-multilevel-menu#14]
Could you please remove this log?
After navigating a while in my page and opening the console, I've seen it full of this log
![captura de pantalla 2018-08-13 a las 12 55 51](https://user-images.githubusercontent.com/5202409/44028081-06970c60-9ef9-11e8-940a-a41a9ab06a70.png)
I think it's because of this log:
https://github.com/ShankyTiwari/ng-material-multilevel-menu/blob/087445604db5d584d22577c0498a0c1a5cd135c2/projects/ng-material-multilevel-menu/src/lib/list-item/list-item.component.ts#L85

**Comment by ShankyTiwari** [comment]
Sorry, I forgot to remove that. In the upcoming update, this will be gone.

**Comment by ShankyTiwari** [comment]
Fixed.
