### ISSUE TITLE
Quality improvement request

### ISSUE THREAD

**Issue by alexIslander** [ShankyTiwari/ng-material-multilevel-menu#147]
Hi ShankyTiwari,
i found this library not long ago and i can see potential in it. It solves many issues and time to have a great multi level menu in the projects. I discovered a code a bit and i have some code quality improvement points.

I would contribute on it! Kindly let me know how can i contribute and how can i get permission to open PR. (i already have a branch waiting for push).

Regards,
AlexIslander

**Comment by ShankyTiwari** [comment]
Hi @alexIslander 

Thanks for your interest and help, really appreciated. BTW There no such defined approval process, You can simply create a new PR & I'll merge it.

Thanks,

**Comment by ShankyTiwari** [comment]
Hi @alexIslander am closing this issue as we have already discussed the next steps [here](https://github.com/ShankyTiwari/ng-material-multilevel-menu/issues/148) and [here](https://github.com/ShankyTiwari/ng-material-multilevel-menu/pull/149#issuecomment-735847670).

**Comment by ShankyTiwari** [comment]
Please feel free to reopen if you feel appropriate whenever you want.
