### ISSUE TITLE
If mouse over full text should display.

### ISSUE THREAD

**Issue by ershad1** [ShankyTiwari/ng-material-multilevel-menu#15]
![image](https://user-images.githubusercontent.com/22111939/44353719-b103d400-a4c9-11e8-8159-86de84503005.png)

label: 'Item 1 (with Font awesome icon)'
but i only show Item 1 ( With

if i put mouse over the text the full text should show as hover text or similar.

**Comment by ShankyTiwari** [comment]
Will do in the next update.
