### ISSUE TITLE
URL & nested menu

### ISSUE THREAD

**Issue by marxsk** [ShankyTiwari/ng-material-multilevel-menu#153]
Let's assume that we have nested menu when item is collapsible (has children, link/onSelected is not defined as it should not change anything). Click on any item means that _currentNode_ is set in selectedListItem(). But when we do mouseOver on collapsible item, we can see that all such items points to same URL. 

Ugly hack: in selectedListItem(event): 

``
if (event.link || event.onSelected) {
  this.currentNode = event;
)
``

It does not solve issue with showing invalid URL but page is not redirected and we are fine. The downside is that click on such parent-item expand item without selecting it. So, selected item is the one were we are on. What is not invalid but better solution might exists. Probably the best idea, will be to change template to not have 'a href' value when link or onSelected are not available.

**Comment by ShankyTiwari** [comment]
HI @marxsk You are correct, The good solution is to not have href if the menu is collapsible and does not redirect to anywhere. I will check this ASAP.

**Comment by ShankyTiwari** [comment]
Fixed in [5.5.3](https://www.npmjs.com/package/ng-material-multilevel-menu/v/5.5.3), @marxsk You can check this now and let me know in case of any issue.

Thanks

**Comment by marxsk** [comment]
Thanks, the patch works as expected.
