### ISSUE TITLE
Support Query Params in URL

### ISSUE THREAD

**Issue by JEVietti** [ShankyTiwari/ng-material-multilevel-menu#156]
Correct me if this is already possible, but it would be nice if the navigationExtras queryParams were read into the actual `<a>` inside of [list-item](https://github.com/ShankyTiwari/ng-material-multilevel-menu/blob/901209d87da1d8946b7521ceaa9d005cf780a36a/projects/ng-material-multilevel-menu/src/lib/list-item/list-item.component.html) so that the interaction could all be handled natively by the browser, and not have to be handled just by the angular router. Especially since as far as I have read/tested, the angular router way will not work when opening a new tab and would require extra code to support that kind of interaction. 

With a possible solution being adding something like this:
`
[queryParams]="node.navigationExtras?.queryParams">
 `, to the existing html. Though it does look like you have a better idea coming up for supplying a directive so that we can write our own template for the `<a>` tag instead of just whats inside it.

**Comment by ShankyTiwari** [comment]
Hi @JEViett I know am replying extremely late, sorry for that. You can write your custom Template, have a look at the [documentation](https://www.npmjs.com/package/ng-material-multilevel-menu#user-content-3-building-custom-templates) and some [demos](https://multilevel-menu-demo.web.app/pages/layout-variations/demo-six/version-one) along with [code](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo/tree/master/src/app/pages/layout-variations/demo-six).
See if it works for you?

Thanks

**Comment by JEVietti** [comment]
Yes, that will work, I needed to update my package for this project, but it seems to be compatible with Angular 9 on 5.5.3. Would you be open to a feature/pull request in the future to provide more fine grained custom templating? I think it would be useful for cases such as mine where I only want to customize the link template and nothing else.
