### ISSUE TITLE
Change font size  of items

### ISSUE THREAD

**Issue by otatar** [ShankyTiwari/ng-material-multilevel-menu#159]
How to change font size of items. Tried with classname, it doesn't work

**Comment by nielcleo** [comment]
Hi otatar, 

you may change the font size by overriding the default scss. try inspecting the element and search for class .anml-items.
or another option is doing custom template for reference please see. [Custom Template Documentation](https://www.npmjs.com/package/ng-material-multilevel-menu#3-building-custom-templates) 

Hope it helps.

Cheer!

**Comment by ShankyTiwari** [comment]
Hi, @otatar Sorry for the delay. From your question, I assume you are using the default List. So in this case you can use a custom class name and use that to apply Stylings as shown below,

**app.component.css:**
```csss
::ng-deep .my-custom-class .anml-link {
  font-size: 30px !important;
}
```
OR

**style.css:**
```css
.my-custom-class .anml-link {
  font-size: 30px !important;
}
```
Just in case if you are planning to write your template then you have to take care of styling and animation on your own as @nielcleo said.

Please let me know if anything is not working for you.

Thanks

**Comment by otatar** [comment]
Thank you @ShankyTiwari, everything is working now. I don't want to write my own template just to change font-size. Maybe it would be best to provide a way to change font size via configuration property binding....actual font size of 16px is a little big for my taste

**Comment by ShankyTiwari** [comment]
@otatar, Good to hear that.

Actually, the plugin does not set any default font size. Instead, It inherits from the Angular Material specifications as the List template is wrapped from the default `MatListItem` component, which has a `16px` font-size as shown below.

```css
.mat-list-base .mat-list-item {
    font-size: 16px;
}
```

Thank you for the configuration property suggestion, meanwhile, you can continue using the class name.

Thanks
