### ISSUE TITLE
Option to use outline icon in the menu

### ISSUE THREAD

**Issue by ershad1** [ShankyTiwari/ng-material-multilevel-menu#16]
Reference to this issue
https://stackoverflow.com/questions/50358473/how-can-i-get-angular-material-icon-to-show-the-outline-in-my-angular-app

i can not use https://material.io/tools/icons/?style=outline
icon
like this one
https://material.io/tools/icons/?search=home&icon=home&style=outline

 {
      label: 'Home',
      link: '/home',
      icon: 'home_outline'
    },

do not work

**Comment by ShankyTiwari** [comment]
Coming in the next update.

**Comment by ShankyTiwari** [comment]
From the last couple of days, I was trying to make it work by applying some decent hack. But, I haven't found any decent way to add this.
To my knowledge and according to [this SO answer](https://stackoverflow.com/questions/50303454/how-to-use-the-new-material-design-icon-themes-outlined-rounded-two-tone-and?answertab=votes#tab-top), there is no official way of adding these icons yet. 
If you have any idea, please do share with me. Though I will keep trying from my end.

**Comment by ShankyTiwari** [comment]
@ershad1 Have you tried using ```_outline``` prefix? Also, I feel this issue is out of the scope of this module, hence am closing it. But if you have any question or suggestion please feel free to reopen.

Thanks.
