### ISSUE TITLE
Do I need to provide MutliLevelMenuService

### ISSUE THREAD

**Issue by otatar** [ShankyTiwari/ng-material-multilevel-menu#165]
Do I need to provide MutliLevelMenuService? I don't use it explicitly anywhere. I use ng-material-multilevel-menu inside lazy loaded module, and this is the error: 

core.js:5967 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(DashboardModule)[MultilevelMenuService -> MultilevelMenuService -> MultilevelMenuService -> MultilevelMenuService]: 
  NullInjectorError: No provider for MultilevelMenuService!
NullInjectorError: R3InjectorError(DashboardModule)[MultilevelMenuService -> MultilevelMenuService -> MultilevelMenuService -> MultilevelMenuService]: 
  NullInjectorError: No provider for MultilevelMenuService!

**Comment by nmgofficial** [comment]
I have the same issue, I have a SharedModule which imports and exports NgMaterialMultilevelMenuModule, but the same error shows.

**Comment by nielcleo** [comment]
Hi @otatar,

To resolve this issue you need to import **_MultilevelMenuService_** as well.
and add it on your providers.

**Comment by ShankyTiwari** [comment]
Hope @otatar , you were able to fix that issue, thanks
