### ISSUE TITLE
Can't bind to 'configuration' since it isn't a known property of 'ng-material-multilevel-menu'

### ISSUE THREAD

**Issue by barkhasjsu** [ShankyTiwari/ng-material-multilevel-menu#169]
core.js:13967 'ng-material-multilevel-menu' is not a known element:
1. If 'ng-material-multilevel-menu' is an Angular component, then verify that it is part of this module.
2. If 'ng-material-multilevel-menu' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

I have followed all steps given in ReadMe.
dependencies added:
 "@angular/animations": "^10.0.3",
  "@angular/cdk": "^10.0.1",
 "@angular/material": "^10.2.7",
"ng-material-multilevel-menu": "^5.5.3"

can you please check what I am missing in my code?

**Comment by ersamrow** [comment]
I've facing same issue, is there any solution?

**Comment by abhinavakhil** [comment]
Change the version -> install this version ->"ng-material-multilevel-menu": "^4.12.4",

npm i angular-material-multilevel-menu@4.12.4

Hope this helps.

**Comment by adhdforge** [comment]
I've facing same issue. any solution yet?

**Comment by ShankyTiwari** [comment]
Try installing latest version,see if that works, Thanks
