### ISSUE TITLE
Menu icons are not visible - Angular 12

### ISSUE THREAD

**Issue by logicielity** [ShankyTiwari/ng-material-multilevel-menu#183]
Hi, 
I am using this but for some reason icons and chevrons are not rendering. I even followed the example to the letter but still nothing, 
![image](https://user-images.githubusercontent.com/39479643/130784028-710d66d2-10fd-4b42-9e79-07bd638cdd0b.png)

**Comment by ShankyTiwari** [comment]
Import Material Icons, Thanks
