### ISSUE TITLE
Routing not working with routes with spaces

### ISSUE THREAD

**Issue by sebastienpattyn93** [ShankyTiwari/ng-material-multilevel-menu#19]
I created a menu that is having links with spaces . When there are no special characters (`%20`) my route is always highlighted in the menu, but when the route contains a space it is not highlighting the right item in the menu.

**Comment by ShankyTiwari** [comment]
Hi @sebastienpattyn93 ,
Can you please provide tiny repo, it would be very helpful.

Thanks,

**Comment by ShankyTiwari** [comment]
Fixed.
