### ISSUE TITLE
ng-material-multilevel-menu with selectedItem/selectedLabel still doesn't work on item with link

### ISSUE THREAD

**Issue by tkarnon** [ShankyTiwari/ng-material-multilevel-menu#191]
I have installed ng-material-multilevel-menu  succesfully and it works grate.
Noticed that selectedItem/selectedLabel doesn't emit on items **with link**, although case #33 was closed.
I must listen to click events on the items in the menu, in order to write to specific log, weather they have link or not.
Is there a workaround?

**Comment by ShankyTiwari** [comment]
hey @tkarnon The thought was

1. Use selectedLabel() callback for Nodes
2. Use selectedItem() callback for Leaf (as in the last node)

LMK if that makes sense!

If not will figure something out, Thanks
