### ISSUE TITLE
Getting warning for Ivy distribution for ng-build on Angular 13

### ISSUE THREAD

**Issue by Shan7anu** [ShankyTiwari/ng-material-multilevel-menu#198]
`Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ng-material-multilevel-menu [es2015/esm2015] (git+https://github.com/ShankyTiwari/ng-material-multilevel-menu.git)
Encourage the library authors to publish an Ivy distribution.`

I'm using `"ng-material-multilevel-menu": "^5.5.3"`

Reference: https://blog.angular.io/upcoming-improvements-to-angular-library-distribution-76c02f782aa4

@ShankyTiwari: Any plans for Ivy distribution?

**Comment by ShankyTiwari** [comment]
Hey @Shan7anu , I have published a new version just now. Sorry for the delay.

Thanks
