### ISSUE TITLE
How to close the other submenu when another item is being clicked

### ISSUE THREAD

**Issue by groot432** [ShankyTiwari/ng-material-multilevel-menu#199]
<img width="490" alt="Screenshot 2022-04-20 at 2 17 57 PM" src="https://user-images.githubusercontent.com/103117393/164189505-2cdbcf58-e43e-4842-a0bd-82b1b6d3ed61.png">
For example in the above screen shot if item 1 is open and user clicks on item 2 ,Item 1 should get closed automatically

**Comment by ShankyTiwari** [comment]
Use `collapseOnSelect: true` config, Thanks
