### ISSUE TITLE
Labels not horizontally aligned

### ISSUE THREAD

**Issue by packe100** [ShankyTiwari/ng-material-multilevel-menu#210]
I've noticed a horizontal misalignment of the first level labels: their box doesn't start at the same x-coordinate because of the preceding icons.

![image](https://user-images.githubusercontent.com/49599138/201404697-c036e0a1-7e8e-4a24-86d3-dc0fce49687e.png)

So my solution was to give the icon container a fixed plain width, with the following component css:
`
::ng-deep .icon-container {
  width: 35px !important;
}
`
... that seems to work correctly:
![image](https://user-images.githubusercontent.com/49599138/201408916-f4623d15-a21d-425e-931e-b3b8caeda1f3.png)

But I don't like the fact that I have to manually choose a specific pixel width that fits all the icons (wich have different widths).
So is there a way, inside my component css, to dinamically compute the width as the max width of the actual icons?

Thank you

**Comment by ShankyTiwari** [comment]
You don't have manually calculate the width, you simply try the below CSS if that works! The `.amml-icon` is a class for all the menu icons.
```css
.amml-icon {
    min-width: 40px !important;
}
```
Let me know the above worked you, Thanks
