### ISSUE TITLE
Angular 16 compatibility

### ISSUE THREAD

**Issue by eddiefrank** [ShankyTiwari/ng-material-multilevel-menu#216]
Due to the removal of the Angular Compatibility Compiler (ngcc) in v16, projects on v16 and later no longer support View Engine libraries.

**Comment by ShankyTiwari** [comment]
hey @eddiefrank  I have updated the project to Angular 16 with this https://github.com/ShankyTiwari/ng-material-multilevel-menu/pull/219 PR. You can now directly install it from NPM.
Sorry for the delay
Thanks
