### ISSUE TITLE
Even though ng-material-multilevel-menu is working with links perfectly but it doesnt change the color of selectItemList 

### ISSUE THREAD

**Issue by Dinesh8291** [ShankyTiwari/ng-material-multilevel-menu#218]
config = {
    paddingAtStart: true,
    interfaceWithRoute: true,
    classname: 'my-custom-class',
    listBackgroundColor: `rgb(208, 241, 239)`,
    fontColor: `rgb(8, 54, 71)`,
    backgroundColor: `rgb(208, 241, 239)`,
    selectedListFontColor: 'red', // this is not working...
    highlightOnSelect: true,
    collapseOnSelect: true,
    rtlLayout: false
};
      <ng-material-multilevel-menu class="my-custom-class" [configuration]='config' [items]='appitems' (selectedItem)="selectedItem($event)">
      </ng-material-multilevel-menu>

**Comment by eddiefrank** [comment]
because new mdc material style
fixed on my fork... 
https://stackblitz.com/edit/gj8gfn?file=src/app/app.module.ts

**Comment by ShankyTiwari** [comment]
Please try the latest version published on NPM. Thanks
