### ISSUE TITLE
Styles are broken when using Menu within <mat-card>

### ISSUE THREAD

**Issue by pklejnowski** [ShankyTiwari/ng-material-multilevel-menu#23]
If `<app-business-menu>` is used inside `<mat-card>` then styles (gray lines) seems to be broken.

![image](https://user-images.githubusercontent.com/28590512/46769068-db645780-ccea-11e8-8091-fe62a20843fb.png)

However I noticed that If i remove `position: relative` here:
![image](https://user-images.githubusercontent.com/28590512/46769110-0058ca80-cceb-11e8-9d9a-90928f68e1a7.png)

Then it looks ok, but gray effect whilst clicking on record doesn't work properly.
![image](https://user-images.githubusercontent.com/28590512/46769153-241c1080-cceb-11e8-8428-bceb9f402e7b.png)

Can you fix it or give me temporary workaround for this?

**Comment by ShankyTiwari** [comment]
Hi there Sorry for the replying late. I will look into it meanwhile can you please help me with the repo.
Thanks,

**Comment by pklejnowski** [comment]
Hi, here u go:
https://stackblitz.com/edit/angular-xait6m?file=src/app/app.component.html

**Comment by StavM** [comment]
as a temporary bypass you can set the inner divider's z-index to 1
until this issue is resolved.
```
ng-list-item mat-divider {
  z-index: 1;
}
```

[DEMO](https://stackblitz.com/edit/angular-ukjgpf?file=src/styles.css)

**Comment by ShankyTiwari** [comment]
Hi, there I have fixed the issue. If you encounter any problem please let me know. 
Thanks for having patience.
