### ISSUE TITLE
Request for new method (selectedLabel)="selectedLabel($event)

### ISSUE THREAD

**Issue by pklejnowski** [ShankyTiwari/ng-material-multilevel-menu#24]
Currently this package has only `(selectedItem)="selectedItem($event)`
It would be great to have `(selectedLabel)="selectedLabel($event)` also.
Because sometimes I'd like to know which Menu Category has been selected thanks to that I could display all its subcategories. Can you add it, please?

**Comment by ShankyTiwari** [comment]
It's Nice to have feature. I will add it.
