### ISSUE TITLE
Does this package works in Angular 7 Project?

### ISSUE THREAD

**Issue by Sibertius** [ShankyTiwari/ng-material-multilevel-menu#28]
Does it work with Angular 7?

**Comment by ShankyTiwari** [comment]
Yes, it does. Let me know if you have issues.

**Comment by JoaoPortella** [comment]
Hi @ShankyTiwari 
ng-material-multilevel-menu@4.9.1 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0
Please, update dependencies...
Thanks in advance!!
