### ISSUE TITLE
some routes don't "activate" the corresponding menu item when redirected by angular

### ISSUE THREAD

**Issue by StavM** [ShankyTiwari/ng-material-multilevel-menu#31]
There's an issue where if you define a route with 'redirect'. the route is recognized by angular, but the menu item isn't responding as you would expect.

so if my route object is this:
```
const routes = [
  {
    path: 'aa', component: ComponentParentComponent, children: [
      { path: '', redirectTo: '/aa/a', pathMatch: 'full' },
      { path: 'a', component: ComponentAComponent },
      { path: 'b', component: ComponentBComponent }
    ]
  }
]
```

and i navigate to 

> localhost:4200/#/aa

the route is changed to `/#/aa/a` by the angular router, though the corresponding menu item, isn't being activated and expanded accordingly.

bug can be seen here : [Stackblitz Demo](https://stackblitz.com/edit/angular-8sdyns?file=src%2Fapp%2Fapp.module.ts)

**Comment by ShankyTiwari** [comment]
I will look into it ASAP,

**Comment by StavM** [comment]
Shanky hope you can take some time and look at this, it's in the recursive function and I suspect it's a bit tricky. only thing stopping me from taking this component to tests & production.

**Comment by nhowarth70** [comment]
Just to add, adding any angular links causes the menu item NOT to be selected. Not sure if its connected or its a different bug?
**For example : menu item IS selected without links**
` items: [

        {
          label: 'Create Organization',
          link: 'organization-wizard',
          icon: 'add'
        },
        {
          label: 'List Organizations',
          link: 'organization-list',
          icon: 'dehaze'
        }
      ],`

**For example : menu item IS selected without links**
` items: [

        {
          label: 'Create Organization',
          link: 'organization-wizard',
          icon: 'add'
        },
        {
          label: 'List Organizations',
          link: 'organization-list',
          icon: 'dehaze'
        }
      ],`

**Comment by Harshi7016** [comment]
Hi,
The issue I have been facing is similar to the bug that is found above, @ShankyTiwari  sir, Can you please look into this and help us out 

Thanks,
Harshith

**Comment by ShankyTiwari** [comment]
@nhowarth70 sure I'll look into from last few months I am very very busy in my day work + plus other activities. But in the next coming week, I'll surely work on these issues.

**Comment by ShankyTiwari** [comment]
Hi @StavM , I looked into the Stackblitz Demo. I found that when we click on Home Link it redirects to the route '/aa'.
`<a routerLink='/aa'>GO HOME </a>`

But in the appitems, we have never specified the route '/aa' as shown below.
```javascript  appitems = [
    {
      label: 'Item 1 (with Font awesome icon)',
      faIcon: 'fab fa-500px',
      items: [
        {
          label: 'Item 1.1',
          link: '/item-1-1',
          faIcon: 'fab fa-accusoft'
        },
        {
          label: 'Item 1.2',
          faIcon: 'fab fa-accessible-icon',
          items: [
            {
              label: 'Item 1.2.2',
              faIcon: 'fas fa-ambulance',
              items: [
                {
                  label: 'I AM ROUTE A',
                  faIcon: 'fas fa-anchor',
                  link: '/aa/a'
                }
              ]
            }
          ]
        }
      ]
    },
    {
      label: 'Item 2',
      icon: 'alarm',
      items: [
        {
          label: 'I AM ROUTE B',
          link: '/aa/b',
          icon: 'favorite'
        },
        {
          label: 'Item 2.2',
          link: '/item-2-2',
          icon: 'favorite_border'
        }
      ]
    },
    {
      label: 'Item 3',
      icon: 'offline_pin',
      onSelected: function () {
        console.log('Item 3');
      }
    },
    {
      label: 'Item 4',
      link: '/item-4',
      icon: 'star_rate',
      hidden: true
    }
  ];
```
The module needs accurate links to work properly. If we change route `/aa` to route `/aa/a`, it is working as expected.
@StavM if you have some other please do share with me, and extremely sorry for taking this much time.
Thanks

**Comment by ShankyTiwari** [comment]
Hi @nhowarth70 , You forgot to add `/` in front of the links, please add `/` it will work properly as shown below,

```javascript
    items: [

    {
      label: 'Create Organization',
      link: 'organization-wizard',
      icon: 'add'
    },
    {
      label: 'List Organizations',
      link: 'organization-list',
      icon: 'dehaze'
    }
]
```

Thanks

**Comment by Harshi7016** [comment]
Hi @ShankyTiwari 

What if there are few extra attributes present along with the link like in the above example if the link is /organization-list?list=1213 or something the menu is not getting highlighted
Is there a way where we can use regular expression or some other property like pathMatch or something similar to make it happen 

Thanks,
Harshith

**Comment by Harshi7016** [comment]
I am new to creating repo 
Since the repo created here is almost similar to the problem that I am going through, I was following the same.

Thanks,
Harshith

**Comment by ShankyTiwari** [comment]
@Harshi7016 Have look at the demo I have provided in #48 that will solve your problem.

**Comment by ShankyTiwari** [comment]
Am closing this issue due to inactivities, feel free to reopen.
