### ISSUE TITLE
How selectedItem works ?

### ISSUE THREAD

**Issue by tmeghe** [ShankyTiwari/ng-material-multilevel-menu#33]
Hello,

Just a quick question about how `(selectedItem)` works, I can't figure it myself. My appItems array has a special field with a special value I want to send to a service when the link is clicked. I tried to add a onSelect property to my object without success.

Could you please give me some advice ?

Thanks a lot,

**Comment by ShankyTiwari** [comment]
Hi @tmeghe ,
To use ```(selectedItem)```  output event, you need to create a method in your component class, which will be called by  ```(selectedItem)``` output event.

For example,
```html
<ng-material-multilevel-menu  
    [configuration]='config' 
    [items]='appitems'
    (selectedItem)="exampleMethod($event)">
</ng-material-multilevel-menu>
````
Now you will create a method called ```exampleMethod($event)``` in your component class.
Eg.
```typescript
exampleMethod($event) {
   console.log.log($event);
}
```
This is how ```selectedItem()``` works.
Similarly, you can try for ```selectedLabel($event)``` as well.

Let me know if you have any further issues.
Thanks,

**Comment by tmeghe** [comment]
Hey @ShankyTiwari,

Thanks for the really quick reply, however, that's what I've done and I have no event showing up. However, it's working fine with `selectedLabel` directive, that's why I was wondering what I've been doing wrong.

`selectedLabel` works fine (it emits the node), but `selectedItem` doesn't emit anything.

**Comment by tmeghe** [comment]
Yes but `selectedItem()`doesn't emit anything ! My menu is built like that (with a recursive function) :

- Root (node)
  - Child 1 (node)
    - Children (item)
    - Children (item)
    - ... etc
  - Child 2 (node)
    - Children (item)
  - ... etc

If I use `selectedLabel()` on `Child 1` it emits an object with the tree of `Child 1's` children. I expect `selectedItem()` on `Children` emitting the object accordingly right ? Or I missed the point here... ?

My problem is that `selectedItem()` doesn't emit a single value here.

**Comment by ShankyTiwari** [comment]
Okay, I understood.
Can I ask you to take a clone of [this repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo) and crosscheck with it?
Please let me know if you are still facing the issue.

**Comment by tmeghe** [comment]
I've tested with the `ng-material-multilevel-menu-demo` repo and it works flawlessly. I reproduced exactly the same behavior in my own code, and it doesn't work.

When I installed node packages before running the `ng-material-multilevel-menu-demo` there was few npm warnings :

``` bash
npm WARN @angular/cdk@7.0.2-ba31c72 requires a peer of @angular/core@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/cdk@7.0.2-ba31c72 requires a peer of @angular/common@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@7.0.2-ba31c72 requires a peer of @angular/animations@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@7.0.2-ba31c72 requires a peer of @angular/core@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@7.0.2-ba31c72 requires a peer of @angular/common@>=7.0.0 but none is installed. You must install peer dependencies yourself.
```

Regarding my code, and the fact that `selectedItem()` doesn't work for me, could it be related to a dependency conflict issue ?

**Comment by ShankyTiwari** [comment]
That repo is in Angular 7, that's why you are getting these warning. 
It has nothing to do with dependencies can you share your array here?

**Comment by tmeghe** [comment]
I think I found what is the problem, my `Children` items are the only items with the `link` property. Just for testing purposes, I removed the `link` property on those items and the `selectedItem()` method emit the item. It doesn't work in the case where `Children` have a link property and therefore use the router to navigate where they are supposed to.

Was my explanation clear enough ?

Fyi, my array (in JSON format) is looking like that :

```son
[
  {
    "label": "Bases",
    "items": [
      {
        "label": "db_1",
        "items": [
          {
            "label": "column_category",
            "link": "table/2",
            "display_title": "column_category",
            "context": "db_1_context",
            "id": "8BrsFGE9I9MpojFTOWks"
          },
          {
            "label": "table_category",
            "link": "table/21",
            "display_title": "table_category",
            "context": "db_1_context",
            "id": "FnJQLMCKcazigZcXh3ot"
          }
        ],
        "id": "txqlKDcnG0M2tSQlKUez"
      },
      {
        "label": "db_2",
        "items": [
          {
            "label": "application_authorization",
            "link": "table/26",
            "display_title": "application_authorization",
            "context": "db_2_context",
            "id": "EjCGSsNHd5tvO74oXCRJ"
          },
          {
            "label": "workplace",
            "link": "table/77",
            "display_title": "workplace",
            "context": "db_2_context",
            "id": "Cppf2vMZAz4fO7A8tqVQ"
          }
        ],
        "id": "jqr4lRhsiYh8B8CG5hV6"
      }
    ],
    "id": "yB0HvHRJGLszJau1y3Wb"
  },
  {
    "label": "Documents",
    "items": [
      {
        "label": "Document 1",
        "link": "document/1",
        "id": "q11OAYyYgUlKYxr38ykO"
      }
    ],
    "id": "f2JyNSDIRm8YhzPnirEI"
  },
  {
    "label": "Vues",
    "items": [
      {
        "label": "View 1",
        "link": "viewspec/46",
        "id": "NqFmsMdJOInCJH0uXcHV"
      },
      {
        "label": "View 2",
        "link": "viewspec/1",
        "id": "MX3L1G5IoPoi4SB1bILk"
      },
      {
        "label": "View 3",
        "link": "viewspec/42",
        "id": "kvDz2MpPjOwqiZgKFkdF"
      }
    ],
    "id": "tSJsu3PbYZrIPjTTOLwH"
  }
]
```

**Comment by ShankyTiwari** [comment]
Yes, you are correct.

**Comment by tmeghe** [comment]
Is it a standard behavior or will you fix it in a future release ?

**Comment by ShankyTiwari** [comment]
Hi @tmeghe , that is the standard behavior. First, it checks the ```link``` property. If found then it will redirect to that link if not found then it will emit the node.

**Comment by tmeghe** [comment]
Thanks for your answer, is there a workaround allowing to emit the node first then redirect to the link provided by the `link` property ? It would be nice to have that feature, in some case it can be useful to emit the node (for instance some data to some service) and navigate to a link.

**Comment by ShankyTiwari** [comment]
Yes, I was actually thinking about this. I will add this feature in next update.
Thanks

**Comment by icoker** [comment]
> Yes, I was actually thinking about this. I will add this feature in next update.
> Thanks

Hi @ShankyTiwari , I'm curious if you ever added this functionality (to use 'link' and selectedItem() at the same time)? If not, do you have plans to add this in a future update?
