### ISSUE TITLE
Not installing on Angular 7

### ISSUE THREAD

**Issue by jijoece** [ShankyTiwari/ng-material-multilevel-menu#37]
Hi,

I'm getting the below warning when running the project with gulp in Angular 7.1.1. Please update the dependencies.

npm WARN ng-material-multilevel-menu@4.9.1 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-material-multilevel-menu@4.9.1 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by jijoece** [comment]
Here is the stackoverflow link with details on this issue. [https://stackoverflow.com/questions/54222824/ng-material-multilevel-menu-not-working-in-angular-7](url)

**Comment by Nabelops** [comment]
Yeah it seems the links don't work with routing in Angular 7
