### ISSUE TITLE
Selected menu background color.

### ISSUE THREAD

**Issue by ershad1** [ShankyTiwari/ng-material-multilevel-menu#4]
Hello, 
If i want to highlight selected menu.

For instance company is clicked. i want different background for companay menu.
 How to do that?
![image](https://user-images.githubusercontent.com/22111939/41789407-03209f66-7671-11e8-8f41-fef5d344da2f.png)

**Comment by ShankyTiwari** [comment]
Hi there,
As of now, this feature is not available but It's a nice to have feature. I was thinking about to something like [this](https://www.cssscript.com/demo/multilevel-accordion-menu-with-plain-html-css) or [AngularJs material's Menu](https://material.angularjs.org/latest/). What do you think?

I will try to put this on the table ASAP.

Thanks

**Comment by ershad1** [comment]
Hi, Godd Afternoon,
Thanks for the reply,
My favourate is angular.io docs
https://angular.io/guide/ngmodules

**Comment by ShankyTiwari** [comment]
Hi there,
Thanks for the suggestion, I will look into it.

**Comment by ShankyTiwari** [comment]
Hi @ershad1 ,
Please update the module to the latest version, I have added this feature.
Also, more demos can be found **[here](http://plugins.codershood.info/#/plugins/ngmm-plugin)**.

**Comment by ershad1** [comment]
Hi @ShankyTiwari 
Thank you very much sir!

**Comment by ShankyTiwari** [comment]
Fixed.

**Comment by ShankyTiwari** [comment]
Hi @adhavD 
Please take the clone of this [repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo), So you can compare the config n all.
Let me know if, you are still facing any issue.

**Comment by ShankyTiwari** [comment]
Okay, I got your point, I have updated the [repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo), please check.

**Comment by ShankyTiwari** [comment]
Maybe in future, will add this feature as well.
