### ISSUE TITLE
svgIcon support

### ISSUE THREAD

**Issue by crawlinknetworks** [ShankyTiwari/ng-material-multilevel-menu#42]
Can you please add support for SVG ICONS in menu item. like below.

    <mat-icon svgIcon="ic-my-icon-name"></mat-icon>

**Comment by ShankyTiwari** [comment]
@crawlinknetworks I'll look into ASAP.

**Comment by ShankyTiwari** [comment]
Hi, @crawlinknetworks sorry for the delay, I have added the support for SVG icons in the menu item.
Thanks

**Comment by g4b0-88** [comment]
How can I implement this attribute (svgIcon)?
