### ISSUE TITLE
Demo page would not open for me

### ISSUE THREAD

**Issue by marcusreese** [ShankyTiwari/ng-material-multilevel-menu#44]
I tried twice to open http://plugins.codershood.info/#/plugins/ngmm-plugin

My Chrome browser says:

> This site can’t be reached
> plugins.codershood.info took too long to respond.
>

**Comment by ShankyTiwari** [comment]
Oh please try after some time, it should open.

**Comment by marcusreese** [comment]
Okay, now I can see it. Thanks.
