### ISSUE TITLE
RouterLinkActive, I don't see

### ISSUE THREAD

**Issue by dkteam** [ShankyTiwari/ng-material-multilevel-menu#47]
Hey bro,

[Sorry for my bad English]
Can you add RouterLinkActive="class-active-name" property to RouterLink.
So we can custom the Acitve Link.
Example: 

![image](https://user-images.githubusercontent.com/34706356/55664407-3bc9f100-5857-11e9-8fbc-3093324bccce.png)

And then,
we can edit "acitve-class":
.active-class{
border-left: 4px solid red;
}

https://angular.io/api/router/RouterLinkActive

Sorry for my bad English
Thanks

**Comment by ShankyTiwari** [comment]
Hey @dkteam , I think you modify the selected item. Can you please check [this repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo), it has all the demos. Let me know if it doesn't work for you.

**Comment by dkteam** [comment]
Hey @ShankyTiwari ,
You mean ".selected-amml-item" class? This class effected activated link and father links.
I don't know what class only effect to activated link?

**Comment by ShankyTiwari** [comment]
Hi, @dkteam I have added a new class for the currently selected menu, have a look.
## Default classes
* ```selected-amml-item```: This class will be applied to currently selected link and it's father links.
* ```active-amml-item```: This class will be applied to the currently selected link.
