### ISSUE TITLE
Interface with route with query params

### ISSUE THREAD

**Issue by pradeepthota07** [ShankyTiwari/ng-material-multilevel-menu#48]
Hi,

I see interfaceWithRoute doesn't work when there are query params in the url. Please let me know if I can achieve this in some other way.

Thanks,
Pradeep

**Comment by ShankyTiwari** [comment]
hi @pradeepthota07 , can you cross check your code with this repo? Let me know if things doesn't work for you.

**Comment by Harshi7016** [comment]
Hi,

Even I face the same issue using ng-material-multilevel- menu, If some details are appended with the link that is specified as reference, It is unable to decide and highlight the corresponding menu.
 

Thanks,
Harshith

**Comment by ShankyTiwari** [comment]
@Harshi7016 can you please create a small repo for this, It would be a huge help. Thanks

**Comment by Harshi7016** [comment]
Hi @ShankyTiwari 

The issue that I am facing right now is similar to the issue raised.

some routes don't "activate" the corresponding menu item when redirected by angular #31

Thanks,
Harshith

**Comment by ShankyTiwari** [comment]
Hi @pradeepthota07 @Harshi7016 guys take a look this [demo](), see if it solves your problem.

Thanks

**Comment by Harshi7016** [comment]
@ShankyTiwari  Thank you so much Sir
This has really helped me a lot
I would like to really appreciate the effort you have put to guide me through this.

Thanks,
Harshith

**Comment by Harshi7016** [comment]
Hi @ShankyTiwari 
Thank you so much for giving a detailed and quick reply and I have followed the same and have got the required result
Thanks again for taking your time to look after this and providing the solution at a much faster rate

Regards,
Harshith

**Comment by ShankyTiwari** [comment]
@Harshi7016 Cool and glad I could help. 
@pradeepthota07 I hope you have also solved your issue if things don't work out for you please feel free reopen this issue.

**Comment by andreyBelov** [comment]
> Hi @pradeepthota07 @Harshi7016 guys take a look this [demo](https://stackblitz.com/edit/angular-4zqp1c), see if it solves your problem.
> 
> Thanks

Hi
I have a similar problem
In your [demo](https://stackblitz.com/edit/angular-4zqp1c), if I type this string in right panel all works as expected and menu item will highlighted
https://angular-4zqp1c.stackblitz.io/one

but if I try this one, item won't highlighted
https://angular-4zqp1c.stackblitz.io/one?params=anydata
