### ISSUE TITLE
Menu Active states incorrect,

### ISSUE THREAD

**Issue by adhavD** [ShankyTiwari/ng-material-multilevel-menu#5]
When I use Json files for menu data... if I click any menu all item get active state...

Also I want to know how any menu select by default without click the menu item.

**Comment by ShankyTiwari** [comment]
Hi @adhavD, thanks for creating the issue here.
Based on our last conversation,  I thought your issue was solved. What version of *ng-material-multilevel-menu* you are using?

But anyway, if you are still facing this issue, then please provide some more light on the issue. Coz am not getting you here, I just checked the code and it's working on my end.

**Comment by adhavD** [comment]
Did you test with external JSon data without hardcode?

**Comment by ShankyTiwari** [comment]
No. Let me check.

**Comment by adhavD** [comment]
If I select any menu item, all items changed to selected state, Here I attached json files and issue [screenshot.](url
![issue](https://user-images.githubusercontent.com/3593066/42305519-e956e982-8048-11e8-958c-6fb542a5c311.png)
![json](https://user-images.githubusercontent.com/3593066/42305570-1f8e1688-8049-11e8-852e-ad6d1483e443.png)


)

**Comment by ShankyTiwari** [comment]
Yes, there is something wrong. I'll fix it soon.

**Comment by adhavD** [comment]
I also know the solution, but I don't know its correct way or not.
We nee some unique id for each menu item like this,
![id](https://user-images.githubusercontent.com/3593066/42305865-88993a76-804a-11e8-9b4a-718b76a70a04.png)

**Comment by ShankyTiwari** [comment]
Yeah, that's how managing it.
I just tested with JSON file and found it's not a bug. You should use ```*ngIf```, while you are fetching your JSON data. try something like this,

```html
<ng-material-multilevel-menu *ngIf="appitems.length > 0" [configuration]='config' [items]='appitems' (selectedItem)="selectedItem($event)"></ng-material-multilevel-menu>
```

**Comment by ShankyTiwari** [comment]
Actually, you get warning in the console, as shown below

![error](https://user-images.githubusercontent.com/15548024/42306830-1e2db528-804e-11e8-9374-a8404e0402b5.png)

The reason for that warning is, the ```items``` input gets an empty array. I will add a better way to show the warning in next update.

**Comment by ShankyTiwari** [comment]
Feel free to reopen the issue, if you have any other problem.
