### ISSUE TITLE
Custom appearance when mouse over

### ISSUE THREAD

**Issue by packe100** [ShankyTiwari/ng-material-multilevel-menu#51]
Hi! Thank you for this great library! I found it very intuitive and effective.

But I have a particular need.
I want to do custom styling on the list items when mouse over event if fired.

So I tryed to sec my custom class name in my component, and then setting the :hover css modifier, but nothing seems to happen.
I'm new about angular and probably I'm doing something wrong.
Thanks for support.

my sidenav-menu.component.ts file:
  ```
config = {
    paddingAtStart: true,
    interfaceWithRoute: true,
    classname: 'side-nav-menu',
    rtlLayout: false
  };
```
sidenav-menu.component.css file:

```
.side-nav-menu .mat-list-item:hover {
  background: dodgerblue;
}
```

**Comment by ShankyTiwari** [comment]
Try writing CSS in styles.css file as shown below, it will work.
```
.side-nav-menu .mat-list-item:hover {
  background: dodgerblue !important;
}
```
OR
```
.side-nav-menu .amml-item:hover {
  background: dodgerblue !important;
}
```

Thanks,

**Comment by packe100** [comment]
Hi Shanky,
thanks a lot for your answer... it worked!

But I don't understand why that styling dosn't have any effet if placed in component's css...

**Comment by StavM** [comment]
It won't work because of [this line](https://github.com/ShankyTiwari/ng-material-multilevel-menu/blob/34124d7d29b6c887605b205b7a4deaa2e3b081db/projects/ng-material-multilevel-menu/src/lib/list-item/list-item.component.html#L2) in the HTML template, getting its value from [here](https://github.com/ShankyTiwari/ng-material-multilevel-menu/blob/34124d7d29b6c887605b205b7a4deaa2e3b081db/projects/ng-material-multilevel-menu/src/lib/list-item/list-item.component.ts#L106) thereby causing background to be an element's inline style.

the only way to override an inline style, is by adding `important` in your css code.

**Comment by ShankyTiwari** [comment]
@packe100 And if you want to write this styling in component.css then you will have use ```ng-deep```. Otherwise, styling won't have any effect if placed in the component's CSS. 
That's how it works.

**Comment by packe100** [comment]
> It won't work because of [this line](https://github.com/ShankyTiwari/ng-material-multilevel-menu/blob/34124d7d29b6c887605b205b7a4deaa2e3b081db/projects/ng-material-multilevel-menu/src/lib/list-item/list-item.component.html#L2) in the HTML template, getting its value from [here](https://github.com/ShankyTiwari/ng-material-multilevel-menu/blob/34124d7d29b6c887605b205b7a4deaa2e3b081db/projects/ng-material-multilevel-menu/src/lib/list-item/list-item.component.ts#L106) thereby defining background as an inline style.
> 
> the only way one can override an inline style, is by adding `important`.

Ok, I didn't get it was an inline style.
Thanks for explanation!

**Comment by packe100** [comment]
> @packe100 And if you want to write this styling in component.css then you will have use `ng-deep`. Otherwise, styling won't have any effect if placed in the component's CSS.
> That's how it works.

Thank you for for explanation.
I've taken a look at official documentation too.

The point is that the styling defined in component.css has effect only on the elements defined in the component template, not the children. Is it right?

So my new styling in component.css is

```
::ng-deep .side-nav-menu .mat-list-item:hover {
  /*color: dodgerblue;*/
  background: dodgerblue !important;
}
```
