### ISSUE TITLE
disabled and specific classes functionality in angular-material-multilevel-menu

### ISSUE THREAD

**Issue by am-awais** [ShankyTiwari/ng-material-multilevel-menu#52]
I get what I need except disabled and different classes feature for nested angular material menu Is it possible to do that or suggest me any other angular material nested menu

What I need:

I need to disable some menus for specific users, it's done by either class or disabled attribute

Its a good feature although and of very common use.

**Comment by ShankyTiwari** [comment]
Hi @am-awais 
1. This package does not support disabled menu item and Ideally, the disabled menu item should be handled from the server only (You should send array from the server).  
2. This package has different classes for respective nested menus, for example, ```level-1```  and ```level-2```. 

This [repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo) has few examples in it, please have a look.
Thanks

**Comment by am-awais** [comment]
Still i didn't find my answer in above repo examples!
1- there is no option in array for disable attribute either form server
2- yes but i told you i need to disable some specific menu item for that i need extra class other then built-in classes like level-1.
Can you provide me stackblitz of my query solution? Please!
 
and if disabled feature is not supported then specific class feature must be in that plugin

**Comment by StavM** [comment]
@am-awais you are correct. there is no unique class for each node.
but, you can always select it via css using the material `ng-reflect-level` attribute.

so it's something like 
```
::ng-deep .level-1 [ng-reflect-level="4"] mat-list-item {
  background: blue !important;
}
```
* yes,  `::ng-deep` is deprecated but its what you got at the moment.
[Stackblitz demo](https://stackblitz.com/edit/angular-vf7qwf?file=src/app/app.component.css)

![image](https://user-images.githubusercontent.com/6926633/59962191-c29f7900-94ea-11e9-8f8e-a69c8dd6564f.png)

**Comment by ShankyTiwari** [comment]
Okay, @am-awais @StavM  am working on it, sorry for the delay.

**Comment by ShankyTiwari** [comment]
**1. Disabled menu:**
![Bug fix 1](https://user-images.githubusercontent.com/15548024/60767428-ad733e80-a0d5-11e9-9e42-278ba3ddcc32.png)
**2. Unique classes for each node:**
![Bug fix 2](https://user-images.githubusercontent.com/15548024/60767432-c2e86880-a0d5-11e9-83f1-aedd479dcfb6.png)

**These features will be available in the next update.**

Thanks

**Comment by am-awais** [comment]
@ShankyTiwari  Thanks

**Comment by ShankyTiwari** [comment]
Hi all,
Added two new features **Disabled menu** and **Unique classes for each node** in the [new update](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.10.8).

Thanks,

**Comment by Anzil-Aufait** [comment]
@ShankyTiwari  , is there any way to add specific class for specific menu item ?? 

**Like :** 

`classname: 'my-class-name`

**Comment by ShankyTiwari** [comment]
No as of now, but if you want to access each list item by the class you can do that shown in below image.

![](https://user-images.githubusercontent.com/15548024/60767432-c2e86880-a0d5-11e9-83f1-aedd479dcfb6.png)


Thanks
