### ISSUE TITLE
tab auto selected when page is reloaded or refreshed

### ISSUE THREAD

**Issue by narendra-sharma** [ShankyTiwari/ng-material-multilevel-menu#54]
i want my tab pre-selected when i reload the page or directly comes to this route in angular 7. Currently it is working on onClick method. Can you please add this feature in future updates?

**Comment by ShankyTiwari** [comment]
@narendra-sharma it's already there, take look at this [repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo)
