### ISSUE TITLE
I need to know where I amon the tree

### ISSUE THREAD

**Issue by Aini452** [ShankyTiwari/ng-material-multilevel-menu#55]
Hi!

I need to know on a click if this is a Label or an Item. 

I've seen the two methods.
(selectedItem)="selectedItem($event)"
 (selectedLabel)="selectedLabel($event)"
but Ive mine on a click and this is when i need to know where i am on the tree.
(click)="toogleSidebar()"
Thx !

**Comment by ShankyTiwari** [comment]
Hi @Aini452,
As far as I can understand from your question is that you want to know **which item is currently selected in the list?** (correct me if am wrong).
In this case, you can save the last selected item somewhere and use it whenever you want.

As of now, this module does not provide a method to give you the currently selected item. And am not sure if this feature falls under the scope of this module.
Please share your suggestion and feel free to reopen the issue.

Thanks
