### ISSUE TITLE
Getting TypeError: _co.selectedItem is not a function

### ISSUE THREAD

**Issue by AzamatRasulov** [ShankyTiwari/ng-material-multilevel-menu#57]
HI. I'm getting pointed above error with initial setup. I'm on Angular 8.0.1, Angular Material 8.0.1 installed.

Routing also doesn't work, due to the issue, I guess.

**Comment by ShankyTiwari** [comment]
Hi @AzamatRasulov,
Am working on a new release of this module with some new features. Can you please tell what was the root cause of the issue? Or something was not right at your end?

Thanks

**Comment by AzamatRasulov** [comment]
Hi, @ShankyTiwari. That wasn't a bug, but unclear documentation. In the "Usage" section you give an html tag of the component with couple properties (selectedItem, selectedLabel) bound to class methods, which doesn't exists in your example.

Just my inattention🤷‍♂️

**Comment by ShankyTiwari** [comment]
@AzamatRasulov Noted, Thanks
