### ISSUE TITLE
can we do expand and collapse all childrens from the component level?

### ISSUE THREAD

**Issue by karthikn21** [ShankyTiwari/ng-material-multilevel-menu#58]

**Comment by ShankyTiwari** [comment]
@karthikn21 Sorry for replying late. 
I can't give you an exact date when I can add this feature but am working on this one.

Thanks

**Comment by ShankyTiwari** [comment]
@karthikn21 Added in [4.12.2](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.12.2).

Thanks
