### ISSUE TITLE
Default Selection

### ISSUE THREAD

**Issue by adhavD** [ShankyTiwari/ng-material-multilevel-menu#6]
Hi,

Any option for Menu selection by default,  when enter the page?

 For example when  i enter in web site home page viewed.. at the same time home menu need to go selected state.

**Comment by ShankyTiwari** [comment]
Hi @adhavD, Unfortunately Routing and it's related user cases are not supported yet. But I am seriously considering to add Routing interface and other routing-related features in next update, please stay with me.
