### ISSUE TITLE
(selectedItem) gets triggered on any routerLink click

### ISSUE THREAD

**Issue by AzamatRasulov** [ShankyTiwari/ng-material-multilevel-menu#64]
Hi. 

Is it intended to fire (selectedItem) when *any* routerLink on the page clicked? I want to use this event for closing sidebar on mobiles after navigation through your component, but can't use it for reasons showed below.

![Unexpected behaviour](https://i.imgur.com/mAa2uSO.gif)

**Comment by cityinspain** [comment]
I do not believe that is the intention, and I'm not noticing the same behavior in my own implementation.
Would you mind providing some of your code?

**Comment by AzamatRasulov** [comment]
Sure.

`
import { Component, OnInit, AfterViewInit } from '@angular/core';
import { AppComponent } from 'src/app/app.component';
import { SidenavStateService } from '../dashboard-layout/sidenav-state.service';
import { BreakpointObserver, BreakpointState } from '@angular/cdk/layout';

@Component({
    selector: 'main-navigation',
    templateUrl: './main-navigation.component.html',
    styleUrls: ['./main-navigation.component.sass']
})
export class MainNavigationComponent implements OnInit, AfterViewInit {
    /**
     * Granted permissions
     */
    permissions: object = this.app.grantedPermissions;

    /**
     * Component config object
     */
    config = {
        classname: 'main-navigation',
        fontColor: '#D2D7E8',
        selectedListFontColor: '#533DFE',
        interfaceWithRoute: true,
        highlightOnSelect: true,
        collapseOnSelect: true
    };

    appitems = [...];

    /**
     * Determines if it's app init state.
     */
    isInit: boolean;

    constructor(
        private app: AppComponent,
        private sidenavService: SidenavStateService,
        private breakpointObserver: BreakpointObserver
    ) {}

    ngOnInit() {
        this.isInit = true;
    }

    ngAfterViewInit() {
        this.isInit = false;
    }

    /**
     * Close sedebar on screens less that 767px wide.
     */
    closeSideBarOnSmallScreen(event) {
        if (!this.isInit) {
            this.breakpointObserver.observe('(max-width: 767px)').subscribe((state: BreakpointState) => {
                if (state.matches) this.sidenavService.onSideNavToggle.emit(false);
            });
        }
    }
}
`

`
<ng-material-multilevel-menu
    [configuration]="config"
    [items]="appitems"
    (selectedItem)="closeSideBarOnSmallScreen($event)"
></ng-material-multilevel-menu>
`

**Comment by ShankyTiwari** [comment]
Hey sorry for replying late, I got your point.
(selectedItem) should be fired, whenever you will click on a router link on the page, which is added in the multilevel menu; not on any other random router link on the page.
And if that's happening then it's a bug, I'll check and try to solve it ASAP. 
Thanks

**Comment by ShankyTiwari** [comment]
Hi @AzamatRasulov Hey sorry for replying late, I checked it and I didn't find any issue with  `(selectedItem)` output event. If the problem still persists, create a working git repo I will surely try to give you a solution.

Thanks for using `ng-material-multilevel-menu`.

**Comment by ShankyTiwari** [comment]
Feel free to reopen.

**Comment by apurv195** [comment]
@ShankyTiwari  i am also facing same issue, when i use **this.router.navigate(['/application/events/events-list'])** from my component **selectedItem** is also triggered
