### ISSUE TITLE
Highlight on load

### ISSUE THREAD

**Issue by g4b0-88** [ShankyTiwari/ng-material-multilevel-menu#65]
Hi, first of all, I love your menu module, it's excellent and exactly what I needed for my project.

I've been working with it a couple months ago, today I was thinking if there is way to highlight (select) the item that matches the route on the site:

The home app loads on:
![image](https://user-images.githubusercontent.com/8822582/62962331-4fb4cf00-bdc4-11e9-8877-374974a1030e.png)

But the item (red rectangle) isn't selected by default:

![image](https://user-images.githubusercontent.com/8822582/62962380-6ce99d80-bdc4-11e9-80f6-e2cce0be5159.png)

![image](https://user-images.githubusercontent.com/8822582/62962436-8be82f80-bdc4-11e9-8af7-61ad6463f384.png)

If there's no feature or setting for this, could you pointing me on a workaround?

Thanks, and congrats for your work.

**Comment by cityinspain** [comment]
Would you mind sharing your code?

**Comment by ShankyTiwari** [comment]
Hi @g4b0-88 can you please create share a small repo? That would be a great help.
Thanks,

**Comment by ShankyTiwari** [comment]
Closing new inactivity, feel free to reopen.
