### ISSUE TITLE
I want one accordion open at the same time.

### ISSUE THREAD

**Issue by MehmetSert** [ShankyTiwari/ng-material-multilevel-menu#66]
Hi,

When I click on the main menu, I want to close other open menus. How can I do that?

Thanks.

**Comment by cityinspain** [comment]
Unless I'm misunderstanding your question, you need to set the collapseOnSelect property in the config you pass to your menu to true.

**Comment by MehmetSert** [comment]
Thank you, as you said I did and it worked. I didn't pay attention to that part.
