### ISSUE TITLE
Send Query parameters and Router Extras in Router navigation

### ISSUE THREAD

**Issue by plebani** [ShankyTiwari/ng-material-multilevel-menu#67]
I would like to send parameters by clicking on a menu item.

Example:
 items: [
                        {
                            label: 'Default',
                            link: '/demo-one',
                            icon: 'favorite',
                            parameters: 'param=123'
                        },
this.router.navigate ([node.link], {queryParams: node.parameters});

How can I do that?

Thank you
Alex

**Comment by ShankyTiwari** [comment]
Yes, it's possible. But unfortunately, I get very limited time due to my day job. I'll add this feature it ASAP and sorry for replying late.
Thanks.

**Comment by ShankyTiwari** [comment]
Hey @plebani , this will be pushed & published tomorrow, thanks for patience .

**Comment by ShankyTiwari** [comment]
Added in [4.11.2](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.11.2). You just need to take care of the URL, that will be generated after passing the Query Params. 
If URL is given in the Array wont match the URL created by Angular Router, then highlighting won't work. Let me know in case of any confusion.

Thanks,
