### ISSUE TITLE
Open the menu when initialised

### ISSUE THREAD

**Issue by PierBJX** [ShankyTiwari/ng-material-multilevel-menu#7]
Hi,
I am using your ng-material-multilevel-menu for a MEAN stack project that I am doing.
It works properly and I would like to thank you for that!

However, I would like to know if there was an option or a way to display all the items when initialized instead of clicking on it ?

Thank you,
Regards,

**Comment by ShankyTiwari** [comment]
Hi there,
Sorry to disappoint you, it's not yet available. But I am gonna add Angular Routing interface in the next update and it will be out probably in the last week of this month or the first week of the next month.
Just one question though, you need this use case while routing between pages or for something else?

**Comment by PierBJX** [comment]
Actually I succeed to add a routing interface like this:

**html:**
`<ng-material-multilevel-menu [items]='appitems' (selectedItem)="redirect($event)"></ng-material-multilevel-menu>`

**component:**
```
appitems = [
    {
      label: "Experiment",
      icon: "details",
      items: [
        {
          label: "View Details",
          link: "experiment/detail"
        },
        {
          label: "View Datasets",
          link: "experiment/dataset"
        }
      ]
    }
  ];

  redirect($event) {
    let url = $event.link + "/" + this.currentExperimentId;
    this.router.navigateByUrl(url);
  }
```
What I would like to know is that instead of having this when the page initialised:
![image](https://user-images.githubusercontent.com/22519163/42717878-1528d5d4-86fc-11e8-8cba-a7944854972e.png)

Is it possible to see the menu already open ? Like this:
![image](https://user-images.githubusercontent.com/22519163/42717895-223d5dee-86fc-11e8-9165-cd362bbf0909.png)

**Comment by PierBJX** [comment]
Alright no problem.
This will be in the next update in the last week of this month or the first week of the next month ?

Thank you.

**Comment by ShankyTiwari** [comment]
Actually, I am on a very tight schedule because of my day job. But it shouldn't take longer than the first week of the next month. I will ping you once I'll publish the update.
Thanks for your patience.

**Comment by PierBJX** [comment]
Alright, no problem.
Thanks for your help !

**Comment by ShankyTiwari** [comment]
Added.

**Comment by PierBJX** [comment]
I don’t see how to make the multilevel list opened by default. How can I make it ?
Thanks

**Comment by ShankyTiwari** [comment]
The menu should expand based on route change automatically.
Or do you want to expand all menus, when component renders it?

**Comment by hectoryo** [comment]
Hi guys, as far as I understand, with this feature, if I route to a direction that is included in one of the routes of the menu, the entry should be highlighted, right?
If this is the case, is it necesay to enable it somwhere? I've updated to version 4.0.1 of the package, but I don't see the meu to change automatically.

**Comment by ShankyTiwari** [comment]
From the above comment, I understand that the menu is not responding to a route change, isn't it?
In that case, can I ask you to refer this [repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo)! 
Please let me know if your issue is solved.

**Comment by ShankyTiwari** [comment]
Cool.

**Comment by PierBJX** [comment]
Yes I would like to expand all menus, when component renders it without route change

**Comment by ShankyTiwari** [comment]
@PierBJX, This was not in the scope of current update. But It's nice to have feature, will do in the next update. It would be something like this (Probably),
{
    label: 'Item 1.1',
    link: '/item-1-1',
    faIcon: 'fab fa-accusoft',
    expanded: true
}
This node and it's parent will be in expanded state. Cool ?

**Comment by hectoryo** [comment]
@ShankyTiwari I've appreciated an unexpected behaviour with the automatic selection.
I'm using an *ngIf to hide the menu when I'm in the login view (wich btw is not included in the menu). When I route to another view and the menu is enabled, no entry is highlighted

**Comment by PierBJX** [comment]
@ShankyTiwari 
Yes it's exactly what I am looking for !

**Comment by ShankyTiwari** [comment]
@hectoryo, It would be very helpful for me to debug if you can reproduce a repo on GitHub or Stackblitz.

Thanks,

**Comment by ShankyTiwari** [comment]
@PierBJX, Will do very soon.

**Comment by hectoryo** [comment]
@ShankyTiwari i've created a fork of your project with the issue replicated
https://github.com/hectoryo/ng-material-multilevel-menu-demo

**Comment by ShankyTiwari** [comment]
@hectoryo , Thank you for the repo, please find the more info in #11.

**Comment by IamSef** [comment]
Hi, may I know how to use the custom class? I tried to change the font size but it won't take effect.

**Comment by ShankyTiwari** [comment]
Hi @IamSef , can you take a clone of this [repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo)! There are examples which uses the custom class with the list.
Thanks

**Comment by doboszt** [comment]
Hi @ShankyTiwari .

Does ng-material-multilevel-menu can handle for example fragments (#) when using routing? For now the menu works fine with routing so when changing url for: **domain.com/example**, the menu is changing the active element.

But when i change the url for **domain.com/example#fragment** the menu cannot correctly regonize it to select a proper item.

Thanks in advance.
