### ISSUE TITLE
Routing not working

### ISSUE THREAD

**Issue by kunalvats1** [ShankyTiwari/ng-material-multilevel-menu#70]
appitems = [
    {
      label: 'Customer',
      icon: 'sentiment_satisfied_alt',
      items: [
        {
          label: 'Views',
          link: '/cardView',
          icon: 'remove_red_eye'
        },
        {
          label: 'Add Customer',
          icon: 'person_add',
          link: '/newCustomer'
        }
      ]
    }
]

why the link is not workable when i click on sidenav item the routing doesn't happen and there is no error also

**Comment by kunalvats1** [comment]
Here is the html code

<ng-material-multilevel-menu [configuration]='config' [items]='appitems'>
        </ng-material-multilevel-menu>

**Comment by cityinspain** [comment]
Hi @kunalvats1 , 

I see that you closed this issue without anyone responding to it. Did you end up figuring out why the link wasn't working?
