### ISSUE TITLE
ERROR in src/app/app.module.ts(36,48): error TS2307: Cannot find module 'ng-material-multilevel-menu'.

### ISSUE THREAD

**Issue by sudharsan203** [ShankyTiwari/ng-material-multilevel-menu#71]
![image](https://user-images.githubusercontent.com/39620680/64840082-7c544480-d617-11e9-956a-44d9d864c541.png)

When i am importing it is showing

**Comment by sudharsan203** [comment]
For Version Angular 8.0 it is working form me but for angular 6.0 not working.

**Comment by ShankyTiwari** [comment]
@sudharsan203, You just need to update your dependencies to 6.1.

**Comment by sudharsan203** [comment]
@ShankyTiwari ,Ok Thank you I had face one more issue #72
