### ISSUE TITLE
color is not highlighting when i click two times on main menu

### ISSUE THREAD

**Issue by sudharsan203** [ShankyTiwari/ng-material-multilevel-menu#72]
I selected Rms link RMS Menu
![AA](https://user-images.githubusercontent.com/39620680/64860131-d7069400-d649-11e9-9985-36e096df8d75.png)
.it is working fine But
When i click again on RMS Menu the highlighting color for selected Rms link is not coming
![AA](https://user-images.githubusercontent.com/39620680/64860201-0d441380-d64a-11e9-8a5e-560b311cef06.png)

**Comment by sudharsan203** [comment]
@ShankyTiwari, would you please suggest me to resolve this issue.

**Comment by sudharsan203** [comment]
> I selected Rms link RMS Menu
> ![AA](https://user-images.githubusercontent.com/39620680/64860131-d7069400-d649-11e9-9985-36e096df8d75.png)
> .it is working fine But
> When i click again on RMS Menu the highlighting color for selected Rms link is not coming
> ![AA](https://user-images.githubusercontent.com/39620680/64860201-0d441380-d64a-11e9-8a5e-560b311cef06.png)

Thank you Issue is cleared.

**Comment by ShankyTiwari** [comment]
Can you give me a repo with error @sudharsan203

**Comment by sudharsan203** [comment]
> Can you give me a repo with error @sudharsan203

Issue Cleared, i Just missed a class.How can i add multiple SVG's.
