### ISSUE TITLE
Different icon in the selected menu item

### ISSUE THREAD

**Issue by MehmetSert** [ShankyTiwari/ng-material-multilevel-menu#75]
Hello,

Is there a feature for specifying different icons in the selected menu item? Or how can I do that?

For example;
imageIcon: 'normal-icon.svg',
activeImageIcon: 'active-icon.svg'

How can I do that?

**Comment by ShankyTiwari** [comment]
@MehmetSert , No as of now it's not there. But it's a good feature I'll try to get it on board ASAP.
Thanks

**Comment by MehmetSert** [comment]
Thanks. Does it comes this feature in one or two days? I immediately need this feature at project  that I worked now.

**Comment by ShankyTiwari** [comment]
Added in [4.11.2](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.11.2)

**Comment by MehmetSert** [comment]
> Added in [4.11.2](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.11.2)

Thank you, I didn't see whether it has use for imageIcon.
