### ISSUE TITLE
How to apply styles on some condition 

### ISSUE THREAD

**Issue by suraj740** [ShankyTiwari/ng-material-multilevel-menu#76]
Hi @ShankyTiwari i just want to apply css to already present classes in module like amml-icon-arrow-container, .amml-icon, etc. based on some condition . How can i do that, is it possible?

**Comment by ShankyTiwari** [comment]
You can do that in ```style.css``` file, for your [reference ](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo/blob/master/src/styles.css)

Thanks

**Comment by suraj740** [comment]
@ShankyTiwari Thanks it worked. Thank you very much.
