### ISSUE TITLE
Highlight listItem Menu on First load

### ISSUE THREAD

**Issue by suraj740** [ShankyTiwari/ng-material-multilevel-menu#77]
Hi @ShankyTiwari  , during first page load the default listitem is not highlighted on menu.
For example:
const routes: Routes = [{path: '',
  redirectTo: '/pages/home',
  pathMatch: 'full'}]

The current route is not highlighted by default.
Its Highlighted on when we selected the list or type route in url.

Thanks!!

**Comment by duard** [comment]
Same problem here

**Comment by ShankyTiwari** [comment]
Hi @suraj740 , @duard try the below configuration,

config = {
    interfaceWithRoute: true,
    highlightOnSelect: true,
  };
Also, can you take a clone of this repo, This repo has almost all the examples, let me know if you have any issue.

Thanks for using ng-material-multilevel-menu.

**Comment by suraj740** [comment]
Thanks @ShankyTiwari for replying, but issue still persists.
I have cloned this repo, but here also its not working on first app load.
I have attached screenshot for the same.
In screenshot also you can see that home is not highlighted on first load only.

<img width="1399" alt="Screenshot 2020-04-24 at 4 29 02 PM" src="https://user-images.githubusercontent.com/24958883/80206227-9a703180-8649-11ea-9f79-2d27d6cda0e8.png">

**Comment by ShankyTiwari** [comment]
I see, tomorrow I'll fix it.

**Comment by ShankyTiwari** [comment]
Okay, So I check it. There was a problem with URL, the home page is displayed on `/pages/home` and in the array URL of Home was `/`. Due to the different URLs, the menu was not highlighting the Home Label.

I have pushed a new commit and here is commit hash [1554f34dafdb856c3f58071c82b74c2c2138fa62](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo/commit/1554f34dafdb856c3f58071c82b74c2c2138fa62), can you please take a new pull again and check.

Thanks

**Comment by suraj740** [comment]
Thanks @ShankyTiwari,  i had tried /pages/home earlier also but that was not working. 
I have pulled your code still the menu is not highlighting on first load.

**Comment by ShankyTiwari** [comment]
Okay, let me check again.

**Comment by ShankyTiwari** [comment]
Hi @suraj740 Can you please check again it's fixed now.

**Comment by suraj740** [comment]
Thanks @ShankyTiwari but still it is not working. Try navigating to localhost:4200 menu is not highlighted until you reload page with http://localhost:4200/pages/home.

**Comment by suraj740** [comment]
Thanks @ShankyTiwari  closing this issue as i got the solution.

**Comment by ShankyTiwari** [comment]
Hi @suraj740 its nice to hear that you have found a solution. Can you please share your solution with us.


Thanks

**Comment by suraj740** [comment]
Hi @ShankyTiwari,  it was bug earlier, after you commited your changes it got resolved.
It was mistake from my side,after login i was not navigating my page to the route which i was used in appItems.

**Comment by ShankyTiwari** [comment]
Alright, Thanks
