### ISSUE TITLE
Refreshing / translating menu

### ISSUE THREAD

**Issue by TheDino000** [ShankyTiwari/ng-material-multilevel-menu#8]
I would like to translate the menu using ngx-translate.
When user changes language I need to reload the menu or replace it's labels.
Is there a way to replace labels or update items?

**Comment by ShankyTiwari** [comment]
I'll add this in next update.

**Comment by TheDino000** [comment]
Thank you.

**Comment by ShankyTiwari** [comment]
Please do not close this issue till I add this feature.

**Comment by TheDino000** [comment]
Of course, no problem.

**Comment by ShankyTiwari** [comment]
Hi there, I have updated the module to check for new array instance. Though I haven't tested with ngx-translate, please check and let me know.

Just in case, when you are using array ```push()```, do not forget to ```slice()``` as shown below,
```javascript
this.appItems.push({
...
});
this.appItems= this.appItems.slice();
```

Thanks and regards,

**Comment by hanyska** [comment]
So how I can translate menu?

**Comment by ShankyTiwari** [comment]
Hi @hanyska , I see. Did you try to console the menu array?
Adn I assume you did something like this,
```javascript
this.appItems.push({
    label: this.translate.instant('users'), 
    icon: 'people', 
    link: '/users'
});
this.appItems= this.appItems.slice();
```

After doing all this, if things don't work for you. Then please share the [https://stackblitz.com/](https://stackblitz.com/) demo, so that I will able to check myself.


Thanks

**Comment by hanyska** [comment]
I prepared stackblitz: https://stackblitz.com/edit/angular-material-sidenav-generate-nav-fzbnwu

**Comment by ShankyTiwari** [comment]
hi @hanyska Thank you for sharing the code, here is an updated code on [Stackblitz](https://stackblitz.com/edit/ng-material-multilevel-menu-ngx-translate-dktu9r)

![image](https://user-images.githubusercontent.com/15548024/80630440-dd7b3c00-8a71-11ea-8e4b-0a9c652abd5e.png)

**Comment by hanyska** [comment]
Excellent answer! Thank you for fast answer! :)
