### ISSUE TITLE
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by ShadowQueen** [ShankyTiwari/ng-material-multilevel-menu#81]
Hello,

I am trying to use this lib in Angular 7, but error "export 'ɵɵdefineInjectable' was not found in '@angular/core'" is appearing after lib is installed. 

Is it possible to use this lib in Angular 7? 
If the answer is yes, what am I doing wrong?

Environment:
_                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.8
Node: 8.12.0      
OS: win32 x64     
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.7
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

Error:

![err](https://user-images.githubusercontent.com/16406109/68073022-a2cb6c00-fd8c-11e9-8564-dec9da6755c0.PNG)

**Comment by ShankyTiwari** [comment]
If possible can you update your App to Angular 8? 
If not you try the previous version of the app which works on Angular 7, for eg try these two version [4.9.4](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.9.4) and [4.9.2](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.9.2)

Thanks

**Comment by ShadowQueen** [comment]
Thank you for the quick answer. Version 4.9.4  is compatible with Angular 7.
