### ISSUE TITLE
ng-material-multilevel-menu has a conflict with amcharts

### ISSUE THREAD

**Issue by johnpankowicz** [ShankyTiwari/ng-material-multilevel-menu#85]
I found this problem as a result of the console.log messages being erroneously left in ng-material-multilevel-menu.js line:514 #80. I was getting thousands of log messages running basically some sample code from your site, inside of another Angular app. I kept isolating other code until I learned that it was a component that was using amcharts, which was the conflict.  

As soon as I removed the component that uses amcharts, the endless logging stopped. The particular chart that was being displayed was a "guage" that was being updated with a timeout. This amchart code was also just demo code off of their site.

amcharts is not using ng-material-multilevel-menu, angular material or even fontawesome icons, so I can't see how there should be a conflict. Also, the timeout values appear to be in seconds, so even if there were, it doesn't explain the thousands of log message that seem to be occurring.

I created a Github repo with the code that reproduces the problem:
[johnpankowicz/ngmenuchart](https://github.com/johnpankowicz/ngmenuchart)
Here also is the [stackblitz](https://stackblitz.com/github/johnpankowicz/ngmenuchart).

I switched to a static pie-chart instead of the gauge with the live data. The problem still remains. So, it is not an issue with setting timeouts.

**Comment by ShankyTiwari** [comment]
The `console.log` messages have been fixed, you can check again. The issue should be fixed, just in case if you are still the issue let me know. For now, I will close the issue, feel free to reopen.


Thanks for using ng-material-multilevel-menu.
