### ISSUE TITLE
Font Awesome Icons printing name to console

### ISSUE THREAD

**Issue by walmanarias** [ShankyTiwari/ng-material-multilevel-menu#89]
the js that  controls and handles using font awesome icons intead of material ones print to the console the name of the icon: here is the line of code that those this:

`getSelectedFaIcon() {
        if (this.isSelected && this.node.activeFaIcon) {
            return this.node.activeFaIcon;
        }
        console.log(this.node.faIcon);
        return this.node.faIcon;
    }`

the line **console.log(this.node.faIcon);** prints all the icons used several times

**Comment by ShankyTiwari** [comment]
Fixed in [#4.12.0](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.12.0), let me know in case of any issue.

Thanks for using `ng-material-multilevel-menu`.
