### ISSUE TITLE
Call function instead of routing

### ISSUE THREAD

**Issue by hectoryo** [ShankyTiwari/ng-material-multilevel-menu#9]
Hi, I'm using your menu to navigate throught different pages, but I want to make a last entry to sign out. Is there any way to call a function that performs the logout when I click?

**Comment by ShankyTiwari** [comment]
Hi there,
Thank you for opening the issue. Right now am working on this module only, once rest of the issues are fixed I will look into this one and I will ping you.
Till then can I suggest you, to use Switch-Case mechanism.  
Thanks.

**Comment by ShankyTiwari** [comment]
Done.
