### ISSUE TITLE
How to open a component in a new tab when press Ctrl+Click in this menu

### ISSUE THREAD

**Issue by sabbircste** [ShankyTiwari/ng-material-multilevel-menu#90]
I want to press Ctrl+Click in a menu to open a component in a new tab. How i can do this?

**Comment by ShankyTiwari** [comment]
Fixed in [#4.12.0](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.12.0), let me know in case of any issue.

Thanks for using `ng-material-multilevel-menu`.
