### ISSUE TITLE
how to apply a custom style for selectedListFontColor property via css 

### ISSUE THREAD

**Issue by narimanmandi** [ShankyTiwari/ng-material-multilevel-menu#92]
i have checked the menu items but i couldn't find any specific class to ensure that it is active or not 
is there anyway to understand ? 
thanks.

**Comment by ShankyTiwari** [comment]
hi @narimanmandi can you try the below config,

```javascript
config = {
    paddingAtStart: true,
    listBackgroundColor: `rgb(208, 241, 239)`,
    fontColor: `rgb(8, 54, 71)`,
    backgroundColor: `rgb(208, 241, 239)`,
    selectedListFontColor: `red`,
  };
```
I would urge you to clone [this repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo/) and this repo has lot of examples.

Thanks for using `ng-material-multilevel-menu`.
