### ISSUE TITLE
how to open menu items in new tab ?

### ISSUE THREAD

**Issue by majidjam** [ShankyTiwari/ng-material-multilevel-menu#93]
i couldn't open menu items in new tab.
how to open menu items in new tab ?

Thanks.

**Comment by ShankyTiwari** [comment]
Fixed in [#4.12.0](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.12.0), let me know in case of any issue.

Thanks for using `ng-material-multilevel-menu`.
