### ISSUE TITLE
Removing horizontal line and title for menu items

### ISSUE THREAD

**Issue by anbalaganr** [ShankyTiwari/ng-material-multilevel-menu#95]
Hi,

Thank you so much for the awesome plugin. I need some help.

How to remove the horizontal line that appeared for every menu item?

And is it possible to add heading for a group of menu items, something like "THEME" and "COMPONENTS" in the below picture?

<img width="170" alt="Screen Shot 2020-04-01 at 2 08 36 AM" src="https://user-images.githubusercontent.com/32128854/78073036-c4716380-73bd-11ea-98f7-a3bcec51d290.png">

Thanks,
Anbalagan R

**Comment by ShankyTiwari** [comment]
Hi @anbalaganr I would urge you to clone [this repo](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo/) and check the demo number **[3](https://github.com/ShankyTiwari/ng-material-multilevel-menu-demo/tree/master/src/app/pages/layout-variations/demo-three)**; This repo has lot of examples.
The third demo will look like this, where the complete look and feel is changed of this menu,

![image](https://user-images.githubusercontent.com/15548024/80198516-cab1d300-863d-11ea-8570-c175acec144a.png)

Let me know if anything doesn't work for you. 

---

> And is it possible to add heading for a group of menu items, something like "THEME" and "COMPONENTS" in the below picture?

No, this menu does not have support for that. 
Alternatively, you can change the appearance of the font by applying CSS using `ng-deep` and make sure to disable the menu you have it won't redirect the user anywhere.

Thanks for using `ng-material-multilevel-menu`.
