### ISSUE TITLE
Bug: dynamically updating menu-items does not update when config is specified

### ISSUE THREAD

**Issue by jepperaskdk** [ShankyTiwari/ng-material-multilevel-menu#96]
It appears that when updating menu-items, e.g. from an API-request or timeout, the menu does not update if a config is specified. I created this stackblitz to show the problem:
https://stackblitz.com/edit/angular-jnvf2d

The third item is only updated in the list after 2 seconds, when config is removed in app.component.ts. If a config is provided, the item does not appear.

**Comment by ShankyTiwari** [comment]
Hi @jepperaskdk ,
This should be the code, only pushing into data inside the array is not enough. 
```javascript
setTimeout(() => {
      this.appitems.push({ label: "Item 3" });
      this.appitems= this.appitems.slice();
}, 2000)
```
Let me know if this doesn't work for you. 

Thanks for using `ng-material-multilevel-menu`.

**Comment by jepperaskdk** [comment]
Ah cool - it seems to work. Is it because the reference has to change for change-detection to happen? How is that related to the config?

**Comment by ShankyTiwari** [comment]
The `slice()` method returns a shallow copy of an array into a new array object, so basically angular treats that array as a new instance. Hence it worked.
