### ISSUE TITLE
Mix routerLink and href

### ISSUE THREAD

**Issue by albinlang** [ShankyTiwari/ng-material-multilevel-menu#98]
Is it possible to mix routerLink and href? In my case I want one of the menu links to open an external website preferable in a new tab (target="_blank").

**Comment by albinlang** [comment]
"externalRedirect: true" seems to solve the external link part of my issue. Is it possible to also specify target blank?

**Comment by ShankyTiwari** [comment]
Fixed in [#4.12.0](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.12.0), let me know in case of any issue.

Thanks for using `ng-material-multilevel-menu`.
